[package]
name = "cdll"
description = "A circular doubly linked list"
authors = ["me@alain.dev"]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/devalain/cll"

[dependencies]
either = "1.6"